### PR TITLE
T473 Homepage & Misc Frontend Updates

### PR DESCRIPTION
**Pull request by maxturer**
It's the redesign!
PR contains:

- homepage styles & JS
- replacement of button class names on all pages (including login pages)
- replacement of a lot of other bootstrap class names to make way for custom code
- moving of the "container" element to individual templates
- temporary simplification of collections results
- change in amount of recent displayed works
- sitewide mobile-responsive fixes
- and, likely, more

To test, I suppose simply checking that I haven't left a file out of the commit (I don't think I did) by viewing the homepage, etc.

### CODE REVIEW

**Comment by dolsysmith** [comment]
@maxturer I think it looks great! Apart from the issue Alex flagged, I'm not seeing any bugs. I'm going to try to merge this branch with the SAML/SSO branch, so that the latter will be up to date.

**Comment by dolsysmith** [comment]
One thing I've noted, which may not need to be fixed as part of this ticket, is that the authenticated works, while viewable as an authenticated user, do not have the download PDF button. You can still download the PDF from the file actions at the bottom, but the button is missing.

**Comment by alepbloyd** [comment]
Woo! Just pulled and rechecked everything, and it looks good to me! 🫡

One day we might want to refactor to hardcode fewer things on the homepage, like the collections text and links, but that definitely sounds like a future iteration to me - especially while talks about collection stuff is still ongoing.

**Comment by maxturer** [comment]
Agreed, I'd been thinking said future iteration could have the collections and header content become content blocks editable in the UI via dashboard, like the standard hyrax "featured researcher" block. But good to know this is (finally) set for now

**Pull request merged**
