### PR TITLE
Initial tests

### PR DESCRIPTION
**Pull request by alepbloyd**
## Part 3/3 of initial RSpec setup

This PR accomplishes two things:
- Removing unused spec files. These were spec file templates that were generated during the initial creation of work-types, but were never filled in with test criteria. We could add them back later, but not serving a purpose here and preventing setup of CI/CD. 
- Adds tests for:
  - Dashboard content as admin vs. content admin
  - Depositing a PDF through dashboard workflow
  - Homepage contents and header/footer links. 
  - Sign-in/sign-out functionality. 
  - Sorting of catalog page by various options. 

We will need to continue adding to the tests, but these tests cover some of the major functionality of the app to start with.

## To test:
- Start docker containers. 
- Start interactive terminal in the app-server container, e.g. `docker exec -it scholarspace-hyrax_app-server_1 /bin/sh`
- Change to scholarspace user with `su scholarspace`
- Create dev/test databases with `bundle exec rails db:create`
- Migrate dev/test databases with `bundle exec rails db:migrate`
- Run `bundle exec rspec`

You should see 40 passing tests, and a coverage report ~56%. 

image

### CODE REVIEW

**Comment by kerchner** [comment]
@alepbloyd I got one failure.  I see that you had 40 examples with 0 failures -- vs. 40 and 1 for me.   Is this a test that you meant to delete?

```
Failures:

  1) Deposit a PDF through dashboard can deposit a pdf
     Failure/Error: visit new_hyrax_gw_etd_path
     
     ActionView::Template::Error:
       undefined method `access_grants' for nil:NilClass
     # /usr/local/rvm/gems/ruby-2.7.3/gems/hyrax-3.6.0/app/services/hyrax/edit_permissions_service.rb:173:in `block in manager_permissions_to_block'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/hyrax-3.6.0/app/services/hyrax/edit_permissions_service.rb:172:in `each'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/hyrax-3.6.0/app/services/hyrax/edit_permissions_service.rb:172:in `manager_permissions_to_block'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/hyrax-3.6.0/app/services/hyrax/edit_permissions_service.rb:66:in `initialize'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/hyrax-3.6.0/app/services/hyrax/edit_permissions_service.rb:38:in `new'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/hyrax-3.6.0/app/services/hyrax/edit_permissions_service.rb:38:in `build_service_object_from'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/hyrax-3.6.0/app/views/hyrax/base/_currently_shared.html.erb:1:in `__usr_local_rvm_gems_ruby_______gems_hyrax_______app_views_hyrax_base__currently_shared_html_erb___662762487998667567_560260'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/hyrax-3.6.0/app/views/hyrax/base/_form_share.html.erb:48:in `__usr_local_rvm_gems_ruby_______gems_hyrax_______app_views_hyrax_base__form_share_html_erb__3376230456358494856_560240'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/hyrax-3.6.0/app/views/hyrax/base/_guts4form.html.erb:44:in `__usr_local_rvm_gems_ruby_______gems_hyrax_______app_views_hyrax_base__guts_form_html_erb__3227931778342925854_559860'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/hyrax-3.6.0/app/views/hyrax/base/_form.html.erb:22:in `block in __usr_local_rvm_gems_ruby_______gems_hyrax_______app_views_hyrax_base__form_html_erb__3020683680141963153_559840'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/simple_form-5.2.0/lib/simple_form/action_view_extensions/form_helper.rb:27:in `block in simple_form_for'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/simple_form-5.2.0/lib/simple_form/action_view_extensions/form_helper.rb:46:in `with_simple_form_field_error_proc'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/simple_form-5.2.0/lib/simple_form/action_view_extensions/form_helper.rb:26:in `simple_form_for'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/hyrax-3.6.0/app/views/hyrax/base/_form.html.erb:1:in `__usr_local_rvm_gems_ruby_______gems_hyrax_______app_views_hyrax_base__form_html_erb__3020683680141963153_559840'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/hyrax-3.6.0/app/views/hyrax/base/new.html.erb:6:in `__usr_local_rvm_gems_ruby_______gems_hyrax_______app_views_hyrax_base_new_html_erb__2458083088653913798_559820'
     # /usr/local/rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-2.2.8/lib/rack/tempfile_reaper.rb:15:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-2.2.8/lib/rack/etag.rb:27:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-2.2.8/lib/rack/conditional_get.rb:27:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-2.2.8/lib/rack/head.rb:12:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-2.2.8/lib/rack/session/abstract/id.rb:266:in `context'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-2.2.8/lib/rack/session/abstract/id.rb:260:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/active-fedora-13.3.0/lib/active_fedora/ldp_cache.rb:26:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/flipflop-2.7.1/lib/flipflop/feature_cache.rb:12:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/railties-5.2.8.1/lib/rails/rack/logger.rb:38:in `call_app'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/railties-5.2.8.1/lib/rails/rack/logger.rb:26:in `block in call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/railties-5.2.8.1/lib/rails/rack/logger.rb:26:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-2.2.8/lib/rack/method_override.rb:24:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-2.2.8/lib/rack/runtime.rb:22:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-2.2.8/lib/rack/sendfile.rb:110:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/railties-5.2.8.1/lib/rails/engine.rb:524:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-2.2.8/lib/rack/urlmap.rb:74:in `block in call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-2.2.8/lib/rack/urlmap.rb:58:in `each'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-2.2.8/lib/rack/urlmap.rb:58:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-test-2.1.0/lib/rack/test.rb:360:in `process_request'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-test-2.1.0/lib/rack/test.rb:163:in `custom_request'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rack-test-2.1.0/lib/rack/test.rb:112:in `get'
     # /usr/local/rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/forwardable.rb:235:in `get'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/capybara-3.39.2/lib/capybara/rack_test/browser.rb:80:in `process'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/capybara-3.39.2/lib/capybara/rack_test/browser.rb:55:in `process_and_follow_redirects'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/capybara-3.39.2/lib/capybara/rack_test/browser.rb:26:in `visit'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/capybara-3.39.2/lib/capybara/rack_test/driver.rb:46:in `visit'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/capybara-3.39.2/lib/capybara/session.rb:280:in `visit'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/capybara-3.39.2/lib/capybara/dsl.rb:52:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/capybara-3.39.2/lib/capybara/dsl.rb:52:in `visit'
     # ./spec/features/deposit_pdf_spec.rb:15:in `block (2 levels) in <top (required)>'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:263:in `instance_exec'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:263:in `block in run'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `block in run'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `run'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:259:in `run'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:646:in `block in run_examples'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `map'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:642:in `run_examples'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/example_group.rb:607:in `run'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `map'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/reporter.rb:74:in `report'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:115:in `run_specs'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:89:in `run'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:71:in `run'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/lib/rspec/core/runner.rb:45:in `invoke'
     # /usr/local/rvm/gems/ruby-2.7.3/gems/rspec-core-3.12.2/exe/rspec:4:in `<top (required)>'
     # /usr/local/rvm/gems/ruby-2.7.3/bin/rspec:23:in `load'
     # /usr/local/rvm/gems/ruby-2.7.3/bin/rspec:23:in `<main>'
     # /usr/local/rvm/gems/ruby-2.7.3/bin/ruby_executable_hooks:22:in `eval'
     # /usr/local/rvm/gems/ruby-2.7.3/bin/ruby_executable_hooks:22:in `<main>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `access_grants' for nil:NilClass
     #   /usr/local/rvm/gems/ruby-2.7.3/gems/hyrax-3.6.0/app/services/hyrax/edit_permissions_service.rb:173:in `block in manager_permissions_to_block'

Finished in 50.08 seconds (files took 26.81 seconds to load)
40 examples, 1 failure

Failed examples:

rspec ./spec/features/deposit_pdf_spec.rb:8 # Deposit a PDF through dashboard can deposit a pdf
```

**Comment by alepbloyd** [comment]
@kerchner - nope, that one should be working! I'll take another look at it.

**Comment by alepbloyd** [comment]
@kerchner - do you have the four `spec/factories` files from previous PR? Those being `admin_sets`, `gw_works`, `permission_templates`, and `users`?

I ask because I just tried commenting out everything in the `spec/factories/permission_templates.rb` file and got the exact error and 1 failure that you got, but I get all passing with that file present.

**Review by kerchner — APPROVED** [review]
💯

**Pull request merged**
