### PR TITLE
T417 dashboard styling

### LINKED ISSUE #417: Some dashboard pages have elements that are missing styling
Photo evidence on single collection page:

dashboard collections page missing styling

This is entirely admin-only, but will be good to fix as it currently looks like an absolute mess.

### PR DESCRIPTION
**Pull request by maxturer**
Will close #417.

Edits & reorders SCSS to prevent weird styling overwrites on certain pages.

Also, organizes SCSS files into the following structure:
stylesheets folder organization

### CODE REVIEW

**Comment by alepbloyd** [comment]
@maxturer - heck yeah heck yeah

Looks like a few reverts of the last few PRs were unintentionally included here that we should remove before merging (the imagemagick source change, the ga4 fix, and some README updates), or is there something else I'm missing here? I thinkkk you could do a `git reset 2260b98` to roll back to the last commit before those reverts. 

Screenshot 2023-10-30 at 5 44 50 PM

**Comment by maxturer** [comment]
@alepbloyd I think those reverts are excluding files I accidentally included in earlier commits, so it should be okay. I had added things like `Dockerfile` and `Gemfile.lock` updates for development purposes, and included them in this PR by mistake, but they're gone now. If I missed anything and there are still extra files, I can take another look.

**Comment by maxturer** [comment]
Some messy Git acrobatics here, but seems like we've managed to exclude the correct files from this PR (commenting here for documentation).

**Comment by alepbloyd** [comment]
@maxturer - here's what ended up working (and accidentally making me the committer oops)

Looks like I did the same thing as you in order to rewind to the commit before the reverts. After that, the issue was that some of the commits (like the readme, docker, gemfile) had already been merged into the master branch. So while having the 417-dashboard-styling branch checked out, I ran git rebase origin/master, which basically makes it like you branched off from the current status of the master branch instead of the outdated version the branch was originally checked out from.

**Comment by alepbloyd** [comment]
Just tested this, and all looks good except that the collection title is showing up as the same color as the background - highlighted the text in this screenshot to show that it's there, but can't see it otherwise. Are you seeing the same thing @maxturer ?
 
Screen Shot 2023-10-31 at 1 46 33 PM

**Comment by maxturer** [comment]
@alepbloyd Well that looks entirely different. And almost exactly like it was before. Let me rebuild and see if we perhaps removed a commit somewhere.

**Comment by maxturer** [comment]
@alepbloyd Currently looks like this on my end (which is how it should look, personal misgivings about the hyrax template aside). Want to rebuild again? Or is that definitely not it

dashboard preview

**Comment by alepbloyd** [comment]
I'll try it again - definitely possible I botched the rebuild.

**Comment by maxturer** [comment]
It looks like the HTML change took effect for you, but none of the CSS. If rebuilding doesn't help, you can try deleting your `/public/assets`, that can help sometimes.

**Comment by alepbloyd** [comment]
Got it! That's what I'm trying now - just ran `rake assets:clobber` to clear out the old assets and remaking now. Will keep you updated.

**Comment by alepbloyd** [comment]
Okay cool, got the changes actually applied now - sorry for the false alarm! 

Are the thumbnails on `/dashboard/my/collections` showing up for you? If they are, I might just have something funky with my derivatives path on my dev server. 

Screen Shot 2023-10-31 at 3 01 03 PM

**Comment by maxturer** [comment]
@alepbloyd They're not, no, this is how the page looks for me. 
collections list

Though on production, it's like this, so I wouldn't be opposed to removing the thumbnail display altogether.
production list

**Comment by dolsysmith** [comment]
Cross-posted in Slack, but I believe the issue with the thumbnails has has to do with how the collections are created when the database is seeded in development. Collections I subsequently create have thumbnails as expected. I am seeing no difference in thumbnail behavior before and after applying the changes in this branch.

**Comment by maxturer** [comment]
This PR should be ready to go now. I'm holding off on working on the other open front end issue until this ticket is resolved (to avoid another inevitable merge conflict), but can merge & close whenever.

**Comment by alepbloyd** [comment]
Re-tested - was having issues with assets not auto-compiling, but once running the precompile assets task, all good!

**Review by alepbloyd — APPROVED** [review]

**Pull request merged**
