### PR TITLE
T419 About & Help pages updated with accordion styles

### LINKED ISSUE #419: Improve readability of about, help, terms pages
Adding GW-ified bootstrap accordions would do for now. Will also try to hear from ScholComm regarding the content of those pages to see if they need a refresh.

### PR DESCRIPTION
**Pull request by maxturer**
This is just the CSS/SCSS for the accordion implementation on the various pages that need them, but as the HTML was changed elsewhere, it should fix #419.

The accordions do a little animation jump when they finish expanding (I am familiar with this issue...), so if you review and it is distracting, feel free to request changes and I'll dig into it.

### CODE REVIEW

**Comment by maxturer** [comment]
Also, could fix this in this PR or just let everyone know about it to be changed elsewhere, there's a duplicate section! There should only be one of these.
Screenshot 2023-11-03 at 5 08 01 PM

**Comment by alepbloyd** [comment]
Will close #438 as well

**Review by alepbloyd — APPROVED** [review]

**Comment by dolsysmith** [comment]
Functionality looks good, though I am also seeing and find bothersome the accordion-animation jitter. I note

**Comment by maxturer** [comment]
Definitely annoying! I have a fix for it on the way once my environment issue is sorted.

**Review by dolsysmith — APPROVED** [review]

**Comment by maxturer** [comment]
Animation jump defeated. Merging!

**Pull request merged**
