### PR TITLE
Dummy works rake task

### PR DESCRIPTION
**Pull request by alepbloyd**
Adds a rake task for generating dummy works for development convenience, and removes old dummy files used for testing - using [Prawn](https://github.com/prawnpdf/prawn) gem to generate simple PDFs instead, which is more flexible. 

Takes optional arguments of `public_works`, `private_works`, and `authenticated_works` with integers. For example:

```
bundle exec rails gwss:create_dummy_works public_works=4 private_works=2 authenticated_works=3 RAILS_ENV=production
```

This would run in the `production` environment, and the first `admin` user would create 4 public works, 2 works private to that admin, and 3 authenticated works visible to logged in users. You can also omit any of these arguments and it will be assumed that you mean 0.

### CODE REVIEW

**Comment by dolsysmith** [comment]
I am getting an error when running the task:
```
Errno::ENOENT: No such file or directory @ rb_sysopen - /opt/scholarspace/scholarspace-hyrax/spec/fixtures/dummy_works/public/public_work_0.pdf
```
Note that I'm not running it with a clean database -- should that make a difference?

**Comment by dolsysmith** [comment]
Some interesting behavior here:
 - Some of the works have the work type of `gw_etd`, but they are in the Default Admin Set, not the ETDs admin set. 
 - Although my admin user has ownership of the works, I can't seem to edit any of them -- the edit button is disabled. 

I tested this with a clean database/Solr index/Fedora instance, and I'm still seeing this behavior. Here are the steps I used to set up the instance (while in the app container as the `scholarspace` user):

```
bundle exec rails db:migrate RAILS_ENV=production
bundle exec rails gwss:prep_new_prod RAILS_ENV=production admin_user=admin2@example.com admin_password=password
mkdir -p spec/fixtures/dummy_works/public # Repeated this step for private and authenticated
bundle exec rails gwss:create_dummy_works public_works=4 private_works=2 authenticated_works=3 RAILS_ENV=production
```

**Comment by dolsysmith** [comment]
Ah! It's not editable because the `license` field has not been populated. Adding a license value allows it to be saved.

For closing this PR, I'd recommend a) adding the empty directories and b) populating the license field in the method(s) that create the works. 

The issue of ETDs not being added to the ETD admin set seems like a separate issue. I'll create a ticket for that.

**Comment by alepbloyd** [comment]
@dolsysmith 

I'm making those adjustments to this now and have a question. 

The way I had it set up, it just finds the first admin user in the database and has that user as the creator for the dummy works  - admin_user = Role.find_by(name: "admin").users.first. 

I think I could change it to also take an email address as an argument, check if that user is in the database and also an admin, and if so - set that to be the user used in the rake task for creating the works. 

If that user isn't in the DB or isn't an admin, would just have it throw an error and exit the task with explanation. 

Do you think that change makes sense?

**Comment by dolsysmith** [comment]
@alepbloyd I think that change makes sense -- thanks!

**Review by dolsysmith — APPROVED** [review]

**Pull request merged**
