### PR TITLE
T99 t313 redesign merge

### PR DESCRIPTION
**Pull request by alepbloyd**
Merging together the redesign work, the local development mode work, and the dockerizing work. 

Docker changes:
- Removal of ImageMagick tar.gz file after installation. 
- Add platforms before `bundle install`, which should prevent errors in installing gems and the need to run it without development. 
- Add all of the `config/environments/[environment | production | development | test].rb` as different templates, all of which are now copied when `docker/scripts/hyrax-config.sh` runs. 
- The `.env` file now requires all three of `SOLR_CORE_TEST`, `SOLR_CORE_DEV`, and `SOLR_CORE_PROD` to be set, and no `SOLR_CORE` variable. 
- Copied solr configurations stored in solr/config to solr/conf, which previously contained unused solr configuration settings. This is more in line with the Hyrax testing applications ([koppie](https://github.com/samvera/hyrax/tree/main/.koppie/solr), [dassie](https://github.com/samvera/hyrax/tree/main/.dassie/solr)).
- Updated the file path in the [Dockerfile-solr file](https://github.com/gwu-libraries/scholarspace-hyrax/blob/t99_t313_merge/Dockerfile-solr) to reflect this change, as well as changes in the `docker/scripts/scholarspace-solr-init.sh` file. 

Development mode seeding:
- When running in development mode, you can run `rails db:seed` in the rails app container (after creating the databases and running the migrations), which will seed the database with the default `admin` and `content-admin` roles, loads Hyrax workflows, creates a `GW Undergraduate Research` journal as a collection, and loads the files in `spec/fixtures/[authenticated_etds | journal_collection | private_etds | public_etds` as ETDs. You can remove any of these files to speed up the process, or add/change them to verify that different files will load correctly.
- Requires `DEV_ADMIN_USER_EMAIL` and `DEV_ADMIN_USER_PASSWORD` variables in your .env file.

### CODE REVIEW

**Comment by dolsysmith** [comment]
Okay, here's an interesting thing. When loaded with legacy data (copies of the Solr core, Fedora file system, `scholarspace-derivatives` directory, and the Fedora and Hyrax databases), the basic functionality I've tested so far seems to work as expected. 

**Except** for the thumbnails, which do not render. As far as I can tell, the derivatives are properly situated and accessible within the container.

The logs show an error being triggered -- it looks like once for every thumbnail that should appear on a given screen -- by [this code](https://github.com/gwu-libraries/scholarspace-hyrax/blob/t99_t313_merge/app/controllers/hyrax/downloads_controller.rb#L21). I haven't managed to trace the inputs to that `show` method`, but I did notice something else that might be relevant. 

1. I took a given GWSS document that exists both on prod and in this test instance: work ID `mc87pr02q`. 
2. On prod, in the Rails console, I ran the following:
```
work = GwWork.find('mc87pr02q')
solr_doc_hash = work.to_solr
solr_doc = SolrDocument.new solr_doc_hash
solr_doc.thumbnail_path
```
The result is ` "/downloads/d504rm170?file=thumbnail"`.  

3. Now I repeated the same step on the instance with the new code & legacy data. The result is totally different: ` "/assets/work-ff055336041c3f7d310ad69109eda4a887b16ec501f35afc0a547c4adb97ee72.png" `. 

Furthermore, I got curious messages at the step `work.to_solr`. (These messages do not appear in prod.)
```
Entity() got something else, testing #to_global_id
Trying to make an Entity for #<GlobalID:0x000055937f21f300 @uri=#<URI::GID gid://scholarspace/GwWork/mc87pr02q>>
Entity() got a GID, searching by proxy
Entity(): attempting conversion on #<Sipity::Entity:0x000055937f21df78>
Entity(): attempting conversion on #<Sipity::Entity:0x000055937f21df78>
Trying to make an Entity for #<Sipity::Entity id: 528, proxy_for_global_id: "gid://scholarspace/GwWork/mc87pr02q", workflow_id: 2, workflow_state_id: 4, created_at: "2023-08-09 14:32:00", updated_at: "2023-08-09 14:32:00">
Entity(): attempting conversion on #<Sipity::Entity:0x000055937f21df78>
 => {"system_create_dtsi"=>"2023-08-09T14:31:58Z", "system_modified_dtsi"=... 
``` 
4. To determine the origin of `solr_doc.thumbnail_path`, I consulted [the SolrDocument module](https://github.com/gwu-libraries/scholarspace-hyrax/blob/75181e3261f210e20c5edb265733fe3d7a287490/app/models/concerns/hyrax/solr_document/metadata.rb#L78), leading me to `CatalogController.blacklight_config.index.thumbnail_field`, which has a value (in both the prod code and the new code) of `thumbnail_path_ss`. 
5. I confirmed that the value for **this** field in the Solr core is the same on both prod and the test instance: `"/downloads/d504rm170?file=thumbnail"`.

I think it's a weird divergence, but I'm not actually sure that's what's causing the error. Will keep looking, but I just wanted to document it in case it proves relevant to the thumbnail issue.

**Comment by alepbloyd** [comment]
@dolsysmith - Huh! I'm not set up with the backup data, so I haven't encountered this yet. I wonder if un-overwriting that `downloads_controller`, or looking at this [downloads_controller](https://github.com/samvera/hyrax/blob/3.5/app/controllers/hyrax/downloads_controller.rb) in the hyrax 3.5.0 repo might give a clue? There are some methods present in there that we don't have in ours.

**Comment by dolsysmith** [comment]
Found another lead [here](
Another lead here: https://github.com/samvera/hyrax/blob/main/app/services/hyrax/thumbnail_path_service.rb).

It looks like the `Hyrax::ThumbnailPathService` is now using `Hyrax.query_service.find_by` to access the thumbnail path; the latter method does seem to exist as such in Hyrax 2. I'm guessing this is a Valkyrie thing, based on what that method does return...

**Comment by dolsysmith** [comment]
Thumbnail issue has been resolved, I think -- it was a matter of how I migrated the data. The thumbnail files on prod were in a subfolder of `scholarspace-derivatives` called `derivatives`. But this version of the app is not expecting that subfolder. Moving the files seems to have solved the issue.

@alepbloyd It looks like you updated the `schema.xml` file in this branch. Was that to bring it into alignment with the Hyrax 3.5 release? (Just noting that [3.5](https://github.com/samvera/hyrax/blob/v3.5.0/solr_conf/conf/schema.xml) uses a slightly different format from what we've been using on prod, which is based on the `schema.xml` from Hyrax v.2.0.

**Comment by alepbloyd** [comment]
@dolsysmith - Looking back at the schema, and I think that was the thought process? If that is creating issues with loading in the backup data from prod because it's based on a different schema, definitely go ahead and change it back!

**Comment by dolsysmith** [comment]
@alepbloyd I don't think it's creating any issues. Just noting that there are some differences vis-a-vis the schema file in the 3.5 Hyrax branch and wondering if we should try to bring our schema into closer alignment with the 3.5 version (to minimize future divergences). But I think what you have is working (as far as I can tell) and didn't have anything to do with the thumbnail issue.

**Pull request merged**
